### ISSUE TITLE
Studio 404 not found

### ISSUE THREAD

**Issue by aykonsvk** [asyncapi/cli#244] opened 2022-02-23 14:06 UTC
#### Describe the bug

I get this error:
```
$ ./node_modules/.bin/asyncapi start:studio
(node:89108) [MODULE_NOT_FOUND] Error Plugin: @asyncapi/cli: Cannot find module '@oclif/plugin-help/lib/command'
Require stack:
- /Users/m/PhpstormProjects/spec/examples/social-media/node_modules/@fmvilas/oclif-plugin-spaced-commands/lib/hooks/init.js
- /Users/m/PhpstormProjects/spec/examples/social-media/node_modules/@oclif/config/lib/config.js
- /Users/m/PhpstormProjects/spec/examples/social-media/node_modules/@oclif/config/lib/index.js
- /Users/m/PhpstormProjects/spec/examples/social-media/node_modules/@oclif/command/lib/command.js
- /Users/m/PhpstormProjects/spec/examples/social-media/node_modules/@oclif/command/lib/index.js
- /Users/m/PhpstormProjects/spec/examples/social-media/node_modules/@asyncapi/cli/bin/run
module: @oclif/config@1.18.3
task: runHook init
plugin: @asyncapi/cli
root: /Users/m/PhpstormProjects/spec/examples/social-media/node_modules/@asyncapi/cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
Studio is running at http://localhost:3210?liveServer=3210
Watching changes on file asyncapi.yaml
```

but browser opens up and shows message` 404 - The requested path could not be found`

#### How to Reproduce

- installed locally/globally using `npm install  @asyncapi/cli`
- when I got first error with oclif, I added more packages. 

```
{
  "dependencies": {
    "@asyncapi/cli": "^0.14.1",
    "@oclif/command": "^1.8.16",
    "@oclif/plugin-help": "^5.1.11",
    "oclif": "^2.4.5"
  }
}
```          

- run `./node_modules/.bin/asyncapi start:studio`  or `./node_modules/.bin/asyncapi new` 

the guide to create a new file works and I can verify that a new file was created.

macOS Monterey, node - v17.6.0, npm - 8.5.1

#### Expected behavior

It will open a studio in the browser with the studio.

**Comment by Souvikns** [comment] 2022-02-23 14:28
@aykonsvk currently CLI shows this warning in production but the development environment works fine you can check this https://github.com/asyncapi/cli/issues/192 I already have this updated oclif to its latest version which you can check https://github.com/asyncapi/cli/pull/203 , we haven't merged this yet since some other PR's will break so waiting for now. 

I am having issue reproducing the bug , I installed the CLI globally and then ran the commands, so my commands look something like this `asyncapi new` and `asyncapi start:studio -f ./asyncapi.yaml` and they are working as intended but I still see the warnings. 


Also can you try running `asyncapi start:studio -f ./path-to-asyncapi-file`. Let me know if you still face the problem.

**Comment by aykonsvk** [comment] 2022-03-01 23:42
I tried it when installed @asyncapi/cli as devDependency locally or globally using the mentioned command above and the result was same. Error and 404.

**Comment by imabp** [comment] 2022-03-08 11:28
As @Souvikns mentioned, we are waiting for PRs to get merged, to make sure, this error no more goes in to production release. 

But for now, @aykonsvk feel free to follow these steps to run locally.
`git clone https://github.com/asyncapi/cli.git`
`npm install`
`bin/run <command> <flags> <paths if any>`

<command> = validate, new, diff, etc
<flags> = -w, -h , etc
<path> = if any command (for ex: diff / validate) requires path.

**Comment by Souvikns** [comment] 2022-03-11 17:47
@aykonsvk can you update to the latest version and check once, your issue should be fixed now, but if it isn't just let me know.

**Comment by aykonsvk** [comment] 2022-03-19 17:03
After the update there is no error in the console. but I still have 404.

Tried new file with 

```
$ node_modules/@asyncapi/cli/bin/run new                                                                  

? name of the file? asyncapi.yaml
? would you like to start your new file from one of our examples? Yes
? What example would you like to use? Streetlights Kafka API - (protocols: kafka-secure)
? open in Studio? Yes
Created file asyncapi.yaml...
Studio is running at http://localhost:3210?liveServer=3210
Watching changes on file asyncapi.yaml
```

And also opening existing with full path:
```
$ node_modules/@asyncapi/cli/bin/run start studio -f /Users/aykon/PhpstormProjects/async-docs/asyncapi.yaml

Studio is running at http://localhost:3210?liveServer=3210
Watching changes on file /Users/aykon/PhpstormProjects/async-docs/asyncapi.yaml
```

<img width="747" alt="image" src="https://user-images.githubusercontent.com/12907442/159130925-ce6c7d74-5d64-4c70-9c69-ced740058274.png">

**Comment by derberg** [comment] 2022-03-23 14:46
@aykonsvk I just installed latest CLI

```
$ asyncapi --version
@asyncapi/cli/0.17.0 darwin-x64 node-v16.4.0
```

All works well for me. I replicated all your steps and see no issues. I see you are working on sources, can you please make sure you are really using latest?

**Comment by andrew-williams-cko** [comment] 2022-04-21 14:29
I also had this 404 issue - but it seems to only happen when `@asyncapi/cli` is installed locally, when installed globally (`npm i -g`), it seems to work fine.

**Comment by aykonsvk** [comment] 2022-04-22 06:27
@andrew-williams-cko Thank you! That helped. Tried to reproduce the problem even in docker and it is not working when package is not globally installed.

**Comment by derberg** [comment] 2022-04-26 16:34
just to clarify @aykonsvk @andrew-williams-cko do you see a use case to use CLI as a local package?

**Comment by derberg** [comment] 2022-05-12 09:24
ok folks, so

1. I added `"@asyncapi/cli": "^0.19.1"` to `devDependencies` in my project
2. created some dummy asyncapi file
3. added script like `"studio": "asyncapi --version && asyncapi start studio"`
4. ran script `npm run studio`
5. Got this
    ```
    @asyncapi/cli/0.19.1 darwin-x64 node-v16.4.0
    Studio is running at http://localhost:3210?liveServer=3210
    Watching changes on file asyncapi.yml
    ```
6. Studio opens and works like a charm, not 404

Maybe you have some ports opened? did you try `p` flag with custom port? Hard to fix without reproducing, or did I misunderstood your use case?

**Comment by Pcrab** [comment] 2022-05-15 12:31
I found if I install with npm globally, `start:studio` works, but if I use yarn or pnpm, it will always return a 404.

**Comment by derberg** [comment] 2022-05-17 14:50
I tried with the latest CLI, installed in my project as a local dependency with YARN and all is good.

I really cannot reproduce it. 
The error looks like connected to https://github.com/asyncapi/cli/blob/master/src/models/Studio.ts#L49. Maybe because of some issues on your side, the `@asyncapi/studio` dependency is not installed, therefore the server cannot host anything from `../../node_modules/@asyncapi/studio/build`. This is my only suspicion as I cannot reproduce. I really do not know 😞

**Comment by mihirkothari25** [comment] 2022-06-09 02:47
I ran into the same issue with pnpm. Installed it as a dev dependency at both the root level and the package level and encountered a 404 when running studio.
It works fine with the global installation of the cli.

**Comment by derberg** [comment] 2022-06-09 10:02
@mihirkothari25 

> I ran into the same issue with pnpm. Installed it as a dev dependency at both the root level and the package level and encountered a 404 when running studio.

can you confirm if `node_modules` inside installed `@asyncapi/cli` you have `@asyncapi/studio` ?

**Comment by mihirkothari25** [comment] 2022-06-09 18:48
@derberg I doesn't contain it.
![Screen Shot 2022-06-09 at 1 47 54 PM](https://user-images.githubusercontent.com/7033628/172921900-7339ce5e-1610-4b9c-b10e-9a6db6ef51a5.png)

**Comment by derberg** [comment] 2022-06-09 20:39
Damn, it is almost completely empty 🤔 at least we know why we get the error, but why the heck deps are not resolved by pnpn...

... looking at docs

> pnpm uses a content-addressable filesystem to store all files from all module directories on a disk. When using npm or Yarn, if you have 100 projects using lodash, you will have 100 copies of lodash on disk. With pnpm, lodash will be stored in a content-addressable storage, so

Looks like it is normal. That if you installed it also globally, it is the only place where it stays and won't go to local package 🤔 but there is also no symlink so what magic is used to import deps... I have no idea 🤣

We need to figę how we can fallback to global location, or in different words, how to safely resolve "build" path relative to node_modules

**Comment by woylie** [comment] 2022-06-23 22:52
I just tried adding the cli (version 0.19.4) as a dev dependency to a yarn 1.22.18 project (no pnpm). I generated a new file with `asyncapi new`, but when I started studio, I got "404 - The requested path could not be found" in the browser as well.

It looks like the dependencies have been installed, though:

<img width="284" alt="image" src="https://user-images.githubusercontent.com/13847569/175424557-8b435174-5640-47b7-82e6-1bc44ced6a7d.png">

I then tried to install the cli globally with yarn, but I got the same result.

**Comment by derberg** [comment] 2022-06-28 14:39
@magicmatatjahu @Souvikns @boyney123 

Hey folks, what do you think about https://github.com/asyncapi/cli/issues/244#issuecomment-1161725030 and 👇🏼 

> or maybe we should modify current approach, and just pull build file from the studio during the release and place in the dist dir

I think we should give it a try and not depend on dependencies and all these different package managers

**Comment by tsauerwein** [comment] 2023-02-10 10:07
The issue still exists with version `0.31.0`. If I install the package locally with `npm install @asyncapi/cli`, I still see a 404 in the browser.

To reproduce:

```
$ nvm install v18.14.0
...
Now using node v18.14.0 (npm v9.3.1)

$ npm install  @asyncapi/cli
$ ./node_modules/.bin/asyncapi --help
All in one CLI for all AsyncAPI tools

VERSION
  @asyncapi/cli/0.31.0 darwin-arm64 node-v18.14.0
...

$ ./node_modules/.bin/asyncapi new
? name of the file? test.yml
? would you like to start your new file from one of our examples? No
? open in Studio? Yes
Created file test.yml...
Studio is running at http://localhost:3210?liveServer=3210
Watching changes on file test.yml
```

Installing it globally works.

**Closed** 2023-04-06 08:38 UTC
Labels: bug
