### ISSUE TITLE
feat: cli should validate only yml, yaml and json extension files

### ISSUE THREAD

**Issue by AayushSaini101** [asyncapi/cli#799] opened 2023-09-12 15:43 UTC
#### Reason/Context
Please try answering a few of those questions
- Why do we need this improvement?

According to the latest version of the CLI, it will generate only yml, yaml and JSON file extensions, but  the validate is still validating the files of different extensions like exe etc

<img width="789" alt="image" src="https://github.com/asyncapi/cli/assets/60972989/e41b2ac8-0719-44c7-83e6-9c0391e6b6a6">

**Comment by AyushNautiyalDeveloper** [comment] 2023-09-12 19:09
hi I would like to work on this. @AayushSaini101 please assign this to me. and also project me to correct direction on where can i start to work on this.

**Comment by Souvikns** [comment] 2023-09-13 07:05
@AyushNautiyalDeveloper, @AayushSaini101 opened the issue and might be working on it so you need to ask him if you want to work on this issue. 

That being said some points I would like to share about the problem 

`asyncapi.ymal.yaml` as per the example shared in the issue is still a valid name for a `.yaml` file so, in theory, this behavior is expected. 

This is the function that loads and parses the spec file, 
https://github.com/asyncapi/cli/blob/4f2412a920dbe125e40db3c0a54c20b83fc7d368/src/commands/validate.ts#L27


If you read the function you will notice that CLI loads the spec from three different ways, from 
- filesystem 
- URL 
- Context


This is how we are reading the file from the filesystem, we don't really check what format of the file is as long as it is valid YAML or JSON. 


https://github.com/asyncapi/cli/blob/4f2412a920dbe125e40db3c0a54c20b83fc7d368/src/models/SpecificationFile.ts#L77

Since we already have a check for file formats while running the new command makes sense to have it for validation as well. Also, I think we can create a new Error Type called `Invalid AsyncAPI file type`(Error name up for debate) since we have more than one scenario for the same error.

**Comment by AyushNautiyalDeveloper** [comment] 2023-09-13 18:16
hi @AayushSaini101 can I work on this task or it is already worked on? please let me know.

**Comment by AayushSaini101** [comment] 2023-09-14 02:13
@AyushNautiyalDeveloper Please take this issue https://github.com/asyncapi/cli/issues/800

**Closed** 2023-09-19 05:45 UTC
Labels: enhancement
